config/routes.rb
Songz::Application.routes.draw do

  

  resources :songs
  resources :albums
  resources :artists
  resources :genres
  match '/artists/add-all/:id' => 'artists#add_all', :via => :post, :as => :add_all
  match '/albums/add-all/:id' => 'albums#add_all', :via => :post, :as => :add_all_songs
  root :to => 'home#index'

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
	has_and_belongs_to_many :songs

	validates :name, :photo, :presence => true
	validates :name, :uniqueness => true
	mount_uploader :photo, MusicUploader
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
	has_and_belongs_to_many :songs
		
	validates :name, :photo, :presence => true
	mount_uploader :photo, MusicUploader
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_and_belongs_to_many :songs
		
	validates :name, :presence => true
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ActiveRecord::Base
	has_and_belongs_to_many :albums
	has_and_belongs_to_many :artists
	has_and_belongs_to_many :genres

	validates :name, :photo, :presence => true
	validates :name, :uniqueness => true
	mount_uploader :photo, MusicUploader
	mount_uploader :mp3, Mp3Uploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		@albums = Album.all
	end

	def show
		@artists = []
		album_id = params[:id]

		@album = Album.find(album_id)
		# this is to take each song on a album and and sees which artist belongs to that song and assigns it to an array
		@album.songs.each do |song|
			@artists << song.artists 
		end
	end

	def new
		@album = Album.new
	end

	def edit
		@album = Album.find(params[:id])
	end

	def create
		@album = Album.new(params[:album])
		if @album.save
			redirect_to albums_path
		else
			render :new
		end

	end

	def update
		@album = Album.find(params[:id])

		if @album.update_attributes(params[:album])
			redirect_to @album
		else
			render :edit
		end
	end

	def destroy
		album = Album.find(params[:id])
		album.delete
		redirect_to albums_path
	end

	def add_all
	    album = Album.find(params[:id])
	    album_name = album["name"].gsub(" ", "+")
	    artist = Artist.find(album["artist_id"])
	    artist_name = artist["name"].gsub(" ","+")
	    album_return = HTTParty.get("http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=b7c58e8da5915f0fea3066e3f29f2362&artist=#{artist_name}&album=#{album_name}&format=json")
	    album_image = album_return["album"]["image"][3]["#text"]
	    tracks = album_return["album"]["tracks"]["track"]

	    begin
	      tracks.each do |track|
	        album.songs << Song.create(:name => track["name"], :remote_photo_url => album_image)
	      end
	    rescue
	    end

	    redirect_to album
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end 

  def show
    artist_id = params[:id]
    @artist = Artist.find(artist_id)
    @albums = @artist.songs.map { |x| x.albums.map{ |album| album}  }

  end

  def create
    @artist = Artist.new(params[:artist])    
    if @artist.save
        redirect_to artists_path
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      redirect_to @artist
    else
      render :edit
    end  
  end

  def destroy
    artist = Artist.find(params[:id])
    Artist.delete(artist)
    redirect_to artists_path
  end

  def add_all
    artist = Artist.find(params[:id])
      artist_name = artist["name"].gsub(" ","+")
      albums_return = HTTParty.get("http://ws.spotify.com/search/1/album.json?q=#{artist_name}")
      albums = albums_return["albums"]

      begin
        albums.each do |album|
          album_plus = album["name"].gsub(" ","+")
          album_return = HTTParty.get("http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=b7c58e8da5915f0fea3066e3f29f2362&artist=#{artist_name}&album=#{album_plus}&format=json")
          album_image = album_return["album"]["image"][3]["#text"]
          if album_image.empty?
            album_image = ""
          end
          artist.albums << Album.create(:name => album["name"], :remote_photo_url => album_image )
        end
      rescue
        
      end

      redirect_to artist
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end 

  def show
    genre_id = params[:id]
    @genre = Genre.find(genre_id)
  end

  def create
    @genre = Genre.new(params[:genre])    
    if @genre.save
        redirect_to genres_path
    else
      render :new
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update_attributes(params[:genre])
      redirect_to @genre
    else
      render :edit
    end  
  end

  def destroy
    genre = Genre.find(params[:id])
    Genre.delete(genre)
    redirect_to genres_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	def index
		@songs = Song.all
	end

	def show
		song_id = params[:id]
		@song = Song.find(song_id)
		begin
			url = "http://lyrics.wikia.com/api.php?artist=#{@artist.name}&song=#{@song.name}&fmt=text".gsub(' ','%20')
			@lyric = HTTParty.get(url)
		rescue
		end
	end

	def new
		@song = Song.new
	end

	def edit
		@song = Song.find(params[:id])
	end

	def create
		@song = Song.new(params[:song])
		if @song.save
			redirect_to songs_path
		else
			render :new
		end

	end

	def update
		@song = Song.find(params[:id])

		if @song.update_attributes(params[:song])
			redirect_to @song
		else
			render :edit
		end
	end

	def destroy
		song = Song.find(params[:id])
		song.delete
		redirect_to songs_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => @album} %>

<%= form_for(@album, :html => {:multipart => true}) do |f| %>

  <ul>
  <% @album.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>

  <div class="field grid_12">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field grid_12">
    <%= image_tag(@album.photo_url) if @album.photo? %>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
    <%= label_tag "Add URL for photo" %>
    <%= f.text_field :remote_photo_url %>
  </div>

  <div class="field grid_12">
    <h4>Songs:</h4>
    <% Song.all.each do |song| %>
      <span class="check-boxes">
        <%= check_box_tag 'album[song_ids][]', song.id, song.in?(@album.songs.to_a) %>
        <%= song.name %>
      </span>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<div class="index">
<% @albums.each do |album| %>
    <div class="index-box grid_3">
    <%= image_tag album.photo, :class => 'photo' %>
    <div class="buttons">
	    <span class="index_name"><%= link_to album.name, album %></span>
	  	<%= link_to 'Edit', edit_album_path(album)%>
	   	<%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }%>
      </div><!--.buttons-->
      
    </div>
  <% end %>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

app/views/albums/show.html.erb
<div class="name">
	<%= @album.name %> <%= link_to 'Edit', edit_album_path(@album), :class => "edit" %>
</div>
<div class="subname">
	Artist: <%= @artists[0][0].name %>
</div>
<div class="main-details grid_8">
	<%= image_tag @album.photo  %>
</div><!--.main-details-->
<div class='meta grid_4'>
	<h4>Tracks</h4>
	<ul>
    <% @album.songs.each do |song| %>
    <li><%= link_to song.name, song %></li>
    <% end %>
   </ul>
   <%= link_to 'Add all songs', :add_all_songs, method: :post %>
</div><!--.meta-->

app/views/artists/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => @artist} %>

<%= form_for(@artist, :html => {:multipart => true}) do |f| %> <!--tells html form that there will be files included here-->
  <ul>
    <% @artist.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <div class="field grid_12">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field grid_12">
    <%= image_tag(@artist.photo_url) if @artist.photo? %>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
    <%= label_tag "Add URL for photo" %>
    <%= f.text_field :remote_photo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<div class="index">
<% @artists.each do |artist| %>
    <div class="index-box grid_3">
    	<%= image_tag artist.photo %>
    	<div class="buttons">
    		<span class="index_name"><%= link_to artist.name, artist %></span>
	    	<%= link_to 'Edit', edit_artist_path(artist) %>
	      	<%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
    	</div><!--.buttons-->
    </div>
<% end %>
</div><!--.index-->

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<div class="name">
	<%= @artist.name %> <%= link_to 'Edit', edit_artist_path(@artist),:class => "edit" %>
</div>
<div class="main-details grid_8">
	<%= image_tag @artist.photo %> 
</div> <!--.main-details-->
<div class='meta grid_4'>
  <h4>Albums</h4>
  <ul>
        <% @albums.uniq.each do |album| %>
    <li><%= link_to album[0].name, album %></li>
        <% end %>
  </ul>
  <%= link_to 'Add all albums', :add_all, method: :post %>
</div><!--.grid_4-->

app/views/genres/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => @genre} %>

<%= form_for(@genre, :html => {:multipart => true}) do |f| %> <!--tells html form that there will be files included here-->
  <ul>
    <% @genre.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <div class="field grid_12">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<div class="index">
<% @genres.each do |genre| %>
    <div class="index-box grid_3">
    	<div class="buttons">
    		<span class="index_name"><%= link_to genre.name, genre %></span>
	    	<%= link_to 'Edit', edit_genre_path(genre) %>
	      	<%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %>
    	</div><!--.buttons-->
    </div>
<% end %>
</div><!--.index-->

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<div class="name">
	<%= @genre.name %> <%= link_to 'Edit', edit_genre_path(@genre),:class => "edit" %>
</div>
<div class="main-details grid_8">
	
</div> <!--.main-details-->
<div class='meta grid_4'>
  <h4>Songs</h4>
  <ul>
        <% @genre.songs.each do |song| %>
        <li><%= link_to song.name, song %></li>
        <% end %>
  </ul>
  <%= link_to 'Add all albums', :add_all, method: :post %>
</div><!--.grid_4-->

app/views/home/index.html.erb
<p class="intro grid_12">
	Songz: We have more songs than you. Now with <%= link_to pluralize(Artist.count, "artist"), artists_path %>, <%= link_to pluralize(Album.count, "album"), albums_path %>, and <%= link_to pluralize(Song.count, "song"), songs_path %>.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Songz</title>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


	<header>
		<nav class="container_12">
			<%= link_to "Songz", root_path, :class => 'logo' %>
			<ul>
    		<li><%= link_to "Artists", artists_path %></li>
    		<li><%= link_to "New Artist", new_artist_path %></li>  
				<li><%= link_to "Albums", albums_path %></li>
    		<li><%= link_to "New Album", new_album_path %></li>
				<li><%= link_to "Songs", songs_path %></li>
    		<li><%= link_to "New Song", new_song_path %></li>
    		<li><%= link_to "Genres", genres_path %></li>
    		<li><%= link_to "New Genre", new_genre_path %></li>
			</ul>
    	</nav>
	</header>
	<div class="container_12">

<%= yield %>

	</div> 
	<footer>
		<div class="container_12">
			<p>&copy; 2012 Beat Hypem Corp :: Dustin - Marc - Jon - Thomas (yang the man!) </p>
		</div>
	</footer>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>

  <ul class="errors">
    <%= object.errors.full_messages.each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  </ul>

 <% end %>

app/views/shared/_youtube.html.erb
<iframe width="300" height="200" src="<%= youtube %>" frameborder="0" allowfullscreen></iframe>

app/views/songs/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => @song} %>

<%= form_for(@song, :html => {:multipart => true}) do |f| %>
  <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <div class="field grid_12">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field grid_12">
    <%= image_tag(@song.photo_url) if @song.photo? %>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
    <%= label_tag "Add URL for photo" %>
    <%= f.text_field :remote_photo_url %>
  </div>

  <div class="field grid_12">
    <%= f.label :mp3 %>
    <%= f.file_field :mp3 %>
  </div>

  <div class="field grid_12">
    <%= f.label :YouTube %>
    <%= f.text_field :you_tube %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<div class="index">
<% @songs.each do |song| %>
    <div class="index-box grid_3">
      <%= image_tag song.photo %>
      <div class="buttons">
      <span class="index_name"><%= link_to song.name, song %></span>
      	<%= link_to 'Edit', edit_song_path(song) %>
      	<%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>  
    </div><!--.index-box-->
  <% end %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<div class='name'>
	<%= @song.name %> <%= link_to 'Edit', edit_song_path(@song), :class => 'edit' %>
</div>
<div class="main-details grid_8">
<span class="subname">
	
</span>
	<%= image_tag @song.photo %> 

</div><!--.main-details-->
<div class="meta">
	<h4>Details</h4>
	<p> 
  <b>Audio:</b>
  <%= audio_tag @song.mp3, :controls => true %>
  </p>
  
  <p>
  <b>Youtube:</b>
  <%= render :partial => 'shared/youtube', :locals => {:youtube => @song.you_tube } %>
  </p>
</div>